### ISSUE TITLE
 USER STORY: Homepage-Header

### ISSUE THREAD

**Issue by raneem-yad** [raneem-yad/project-portfolio-1#1]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Epic | HomePage |
| User Story | - |

## Description
**As a** visitor ,**I want** to see the Header in the page, **So that** I  know more about this site.

## Acceptance Criteria
1. The header page will shown with a navigation bar above it.
2. The header is responsive on Desktop and mobile viewports 
3. The header is compatible with Chrome and Safari.

## Tasks
- [ ] Implementing the header using HTML and CSS.
- [ ] Testing on Desktop and mobile using Devtools.
- [ ] Testing on different web browsers.
