### ISSUE TITLE
USER STORY: HomePage - Introduction Section

### ISSUE THREAD

**Issue by raneem-yad** [raneem-yad/project-portfolio-1#2]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Epic | HomePage |
| User Story | Website Introduction Section |

## Description
**As a** visitor, **I want** to see the info on the first page, **So that** I  know what services the website provides.

## Acceptance Criteria
1. The Introduction page will show three types of articles talking about: 
     1- Healthy Recipes
     2- Nutritions Tipps 
     3- Why trust us
3. The header is responsive on Desktop and mobile viewports 
4. The header is compatible with Chrome and Safari.

## Tasks
- [ ] Implementing the header using HTML and CSS.
- [ ] Testing on Desktop and mobile using Devtools.
- [ ] Testing on different web browsers.
