### ISSUE TITLE
USER STORY: Presenting articles on pages. 

### ISSUE THREAD

**Issue by raneem-yad** [raneem-yad/project-portfolio-1#3]
## User Story
| Metadata | Description |
| -------- | ----------- |
| Epic | Seconds Pages |
| User Story | Presenting articles on pages.  |

## Description
**As a** visitor, **I want** to see the all articles that the website provides, **So that** I  can educate myself more on healthy habits.

## Acceptance Criteria
1.  Showing different types of articles.
2. The articles are responsive on Desktop and mobile viewports 
3. The articles are compatible with Chrome and Safari.

## Tasks
- [ ] Implementing the different types of articles.
- [ ] Testing on Desktop and mobile using Devtools.
- [ ] Testing on different web browsers.
